-- CreateTable
CREATE TABLE "Tipo_curso" (
    "ID_TIPO_CURSO" SERIAL NOT NULL,
    "NOMBRE_TIPO_CURSO" TEXT NOT NULL,

    CONSTRAINT "Tipo_curso_pkey" PRIMARY KEY ("ID_TIPO_CURSO")
);

-- CreateTable
CREATE TABLE "Profesor" (
    "ID_PROFESOR" SERIAL NOT NULL,
    "NOMBRE_PROFESOR" TEXT NOT NULL,
    "APELLIDO_PROFESOR" TEXT NOT NULL,
    "CEDULA_PROFESOR" TEXT NOT NULL,
    "CELULAR_PROFESOR" TEXT NOT NULL,
    "CORREO_PROFESOR" TEXT NOT NULL,

    CONSTRAINT "Profesor_pkey" PRIMARY KEY ("ID_PROFESOR")
);

-- CreateTable
CREATE TABLE "Nivel_curso" (
    "ID_NIVEL_CURSO" SERIAL NOT NULL,
    "NIVEL_CURSO" INTEGER NOT NULL,

    CONSTRAINT "Nivel_curso_pkey" PRIMARY KEY ("ID_NIVEL_CURSO")
);

-- CreateTable
CREATE TABLE "Curso" (
    "ID_CURSO" SERIAL NOT NULL,
    "NIVEL" INTEGER NOT NULL,
    "PROFESOR" INTEGER NOT NULL,
    "TIPO" INTEGER NOT NULL,
    "NOMBRE_CURSO" TEXT NOT NULL,

    CONSTRAINT "Curso_pkey" PRIMARY KEY ("ID_CURSO")
);

-- AddForeignKey
ALTER TABLE "Curso" ADD CONSTRAINT "Curso_TIPO_fkey" FOREIGN KEY ("TIPO") REFERENCES "Tipo_curso"("ID_TIPO_CURSO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Curso" ADD CONSTRAINT "Curso_PROFESOR_fkey" FOREIGN KEY ("PROFESOR") REFERENCES "Profesor"("ID_PROFESOR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Curso" ADD CONSTRAINT "Curso_NIVEL_fkey" FOREIGN KEY ("NIVEL") REFERENCES "Nivel_curso"("ID_NIVEL_CURSO") ON DELETE RESTRICT ON UPDATE CASCADE;
